# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the comma`nds below to build your repository.
        # Install system components
          - sudo apt-get update
          - sudo apt-get install -y curl gnupg apt-transport-https
        # Import the public repository GPG keys
          - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        # Register the Microsoft Product feed
          - sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'
        # Update the list of products
          - sudo apt-get update
        # Install PowerShell
          - sudo apt-get install -y powershell
          - pwsh IntegrationTest.ps1
